apiVersion: 1

dataSources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  editable: true

- name: Jaeger
  type: jaeger
  url: http://jaeger:16686
  access: proxy
  editable: true