{
 "title": ".NET Performance Counters",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "System.Runtime performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "GC Allocation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_memory_usage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * (delta(process_cpu_time{state='user'}[$__rate_interval])/ignoring(state)(process_cpu_count* 30))",
     "legendFormat": "cpu_utilization"
    }
   ]
  },
  {
   "title": "Number of GC Generations over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_collections_count",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "TheadPool Completed Items Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "JIT Compilation Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_compilation_time",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "JIT IL Compiled Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_il_compiled_size",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": ".NET Timer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_timer_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JIT Methods Compiled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_methods_compiled_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": ".NET Assemblies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_assemblies_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Generations Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_collections_count",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": ".NET Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}