{
 "title": "Orders API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "total_orders" }
   ]
  },
  {
   "title": "Current order count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "total_orders_count" }
   ]
  },
  {
   "title": "Rate total orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(total_orders[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Products per order histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "products_per_order_Products_bucket"
    }
   ]
  },
  {
   "title": "Rate of weather forecasts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(total_weatherforecast_count_Weather_forecast_count[$__rate_interval])"
    }
   ]
  }
 ]
}